apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql22
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: myapp
  
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
          
        volumeMounts:
        - name: sql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: qas
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
