apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
spec:
  replicas: {{.Values.replicaCount}}
  
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
      - name: todo-ui
        image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
        # image: acr222.azurecr.io/microtodo:22
        ports:
        - containerPort: 80
