name: Build and Push to ACR

on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: microtodo
      IMAGE_TAG: v2
      ACR_NAME: acr22
      ACR_LOGIN_SERVER: acr22.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: e8b48fab-a267-4787-8581-a861d93d22d7
          tenant-id: bf1ea6d6-1a42-4fc7-b801-aaddf0e26bfe
          subscription-id: 50d7f43f-63cc-4cf6-8829-1542e9da33ea

      - name: Log in to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
