name: deploy to akss

on:
 # workflow_dispatch:
 workflow_run: 
  workflows: ["Build and Push to ACR"]
  types: 
   - completed

permissions:
 id-token: write
 contents: write

jobs:
  deploy:
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v4
       with:
        token: ${{ secrets.GITHUB_TOKEN }}
     - name: Update deployment image
       run: |
        sed -i "s|image:.*|image: acr222.azurecr.io/microtodo:${{ github.event.workflow_run.run_number }}|g" manifests/templates/deployment.yaml
     - name: helm deploy
       run: |
        helm upgrade --install dev ./manifests
     - name: Commit changes
       run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add manifests/templates/deployment.yaml
          git commit -m "Update image tag to ${{ github.run_number }}" || exit 0
          git push
     # - name: Azure Login
     #   uses: Azure/login@v2.3.0
     #   with:
     #        client-id: 49f815ef-c5cb-4376-855a-c61b5bfb51a6
     #        tenant-id: c9e1671a-0acd-4412-ba55-018fc27d1f62
     #        subscription-id: 8fc57fc2-9cc4-4bcb-8c0f-315512d0cba3
     # - name: aks connect
     #   run: az aks get-credentials --resource-group Vivek_AKS_RG --name aks-cluster --overwrite-existing
     # - name: deploy
     #   run: |
     #         kubectl apply -f manifests/deployment.yaml
     #         kubectl apply -f manifests/service.yaml
     #         kubectl apply -f manifests/ingress.yaml
     # - name: deployment check
     #   run: kubectl get deploy




 
